server:
  port: 8081
spring:
  application:
    name: WeChatControl
  #设置static目录为默认的访问路径
  mvc:
    static-path-pattern: /static/**
  #配置thymeleaf 当使用thymeleaf但是不配置模板的时候 本模块的所有controller转发，重定向都会错误
  #并且配置模板后(定义了前后缀) 本模块中所有的html 将只能在templates目录下使用
#  thymeleaf:
#    mode: HTML
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: .html
#    #使用模板路径
#    check-template-location: true
#    cache: false
  #使用alibaba数据源建立数据库连接
  datasource:
    url: jdbc:mysql://47.115.60.225:3310/Prod?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: lh1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #redis配置
  redis:
    database: 1
    host: 47.115.60.225
    port: 6379
    timeout: 3000
    password: lh1234
    lettuce:
      pool:
        min-idle: 5

#配置日志记录工具
logging:
  level:
    org:
      #日志信息的打印
      springframework: error
    com:
      example:
        mapper: debug

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启懒加载
    lazy-loading-enabled: true
    #开启按需加载
    aggressive-lazy-loading: true
    #开启二级缓存
    cache-enabled: true
    #设置 springboot 配置的日志工具 实现mybatis的打印日志接口(这样才能打印出每条语句的结果，否侧就是只显示sql语句 没有表数据显示)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.entity